### PR TITLE
Need to prefix command with node

### PR DESCRIPTION
**Pull request by jonasfj**

### CODE REVIEW

**Comment by jonasfj** [comment]
We want it so that `npm install -g taskcluster-lib-docs` should installs the binary in PATH... I think this is a step in that direction, I didn't test it...

**Review by djmitche — CHANGES_REQUESTED** [review]
https://docs.npmjs.com/files/package.json#bin suggests this should be

```
"upload-project-docs": "./lib/upload-project-docs.js"
```

**Comment by jonasfj** [comment]
Then the scripts have to start with:

#!/usr/bin/env node

Aren't we missing that?

Den 2. apr. 2017 8.40 AM skrev "Dustin J. Mitchell" <
notifications@github.com>:

**Comment by djmitche** [comment]
I guess that would explain why https://github.com/taskcluster/taskcluster-lib-docs/blob/master/build-docker-image.sh#L28 is required?  I had assumed it was because `npm install` in a directory doesn't do a global install.  If you can make that work better (fixing the Dockerfile), then r+ :)

**Review by djmitche — APPROVED** [review]

**Pull request merged**
