### PR TITLE
Add workers as tier

### PR DESCRIPTION
**Pull request by jonasfj**
Okay, I have no idea if this right...
@imbstack, @djmitche, I assume one or both of you have some grand design vision for docs organization...

I suspect we need two tiers for workers...
1. workers (generic-worker, docker-worker, taskcluster-worker, script-worker)
2. worker-types (b2gtest, github-worker, etc...)

1) would describe how tc-worker is architectured, the code, how to configure it and deploy it...
2) would document a specific deployment of tc-worker... ie. once I have a configuration file I want to generate the payload schema as well as documentation specific to this workerType...
I imagine each plugin in tc-worker would export docs, such that docs is exported depending on which plugins are enabled in the workerType configuration...

### CODE REVIEW

**Comment by djmitche** [comment]
This PR looks good.  I don't like the idea of individual workerTypes being described in the docs, though -- it blurs the distinction between data and configuration.

I would support something like:
 * queue registers workerTypes
   * registration includes schema, description
   * registration would occur at worker startup and include an expiration, so that old workerTypes eventually disappear
   * with an option for "hidden" workerTypes for tests, dynamically generated, etc.
 * new tools UI to browse workerTypes
    * this would replace most users' use of the AWS provisioner tool as a way to view queues and queue lengths

The docs could then point to this tool as a way of determining what configuration a specific workerType has.  It would also enable the queue to do payload verification.

**Review by djmitche — APPROVED** [review]
curiously, this is already documented in README.md

**Review by imbstack — APPROVED** [review]

**Comment by jonasfj** [comment]
> I don't like the idea of individual workerTypes being described in the docs, though -- it blurs the distinction between data and configuration.

Yeah, so my thinking was opposite here... let's talk about this after meeting tomorrow...

> It would also enable the queue to do payload verification.

I have mixed feelings about this... on the one hand no harm... except maybe denial of service through evil JSON schemas... but that seems acceptable.. .However, `malformed-payload` error is a decent solution for this; and will still have to exist anyways...

**Comment by jonasfj** [comment]
Appears fixed in 3.3.2, thanks :)

**Pull request closed without merging**
